<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Blog.Infra.Messaging</RootNamespace>
    <AssemblyName>Blog.Infra.Messaging</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\Blog.Core.Contract\Blog.Core.Contract.csproj" />
    <ProjectReference Include="..\..\Core\Blog.Core.Domain\Blog.Core.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.0" />
  </ItemGroup>
</Project>
