namespace AVICRM.Services;

/// <summary>Built-in seed catalog for UI chrome (not post content). FA / EN / AR.</summary>
public static partial class UiTranslationCatalog
{
    public static readonly (string Key, string Group, string Fa, string En, string Ar)[] All =
    {
        ("nav.posts", "nav", "نوشته‌ها", "Posts", "المقالات"),
        ("nav.bookmarks", "nav", "نشان‌ها", "Bookmarks", "الإشارات"),
        ("nav.notifications", "nav", "اعلان‌ها", "Notifications", "الإشعارات"),
        ("nav.admin", "nav", "پنل مدیریت", "Admin", "الإدارة"),
        ("nav.login", "nav", "ورود", "Login", "دخول"),
        ("nav.register", "nav", "ثبت‌نام", "Register", "تسجيل"),
        ("nav.logout", "nav", "خروج", "Logout", "خروج"),
        ("nav.language", "nav", "زبان", "Language", "اللغة"),

        ("btn.save", "button", "ذخیره", "Save", "حفظ"),
        ("btn.cancel", "button", "انصراف", "Cancel", "إلغاء"),
        ("btn.delete", "button", "حذف", "Delete", "حذف"),
        ("btn.edit", "button", "ویرایش", "Edit", "تعديل"),
        ("btn.create", "button", "ایجاد", "Create", "إنشاء"),
        ("btn.search", "button", "جست‌وجو", "Search", "بحث"),
        ("btn.filter", "button", "فیلتر", "Filter", "تصفية"),
        ("btn.submit", "button", "ارسال", "Submit", "إرسال"),
        ("btn.back", "button", "بازگشت", "Back", "رجوع"),
        ("btn.approve", "button", "تأیید", "Approve", "موافقة"),
        ("btn.reject", "button", "رد", "Reject", "رفض"),
        ("btn.resolve", "button", "حل", "Resolve", "حل"),
        ("btn.dismiss", "button", "رد کردن", "Dismiss", "تجاهل"),
        ("btn.duplicate", "button", "کپی", "Duplicate", "نسخ"),
        ("btn.soft_delete", "button", "حذف نرم", "Soft delete", "حذف ناعم"),
        ("btn.report", "button", "گزارش", "Report", "إبلاغ"),
        ("btn.bookmark", "button", "نشان", "Bookmark", "إشارة"),
        ("btn.bookmarked", "button", "نشان‌شده", "Bookmarked", "مُعلَّم"),
        ("btn.like", "button", "پسند", "Like", "إعجاب"),
        ("btn.restore", "button", "بازگردانی", "Restore", "استعادة"),
        ("btn.on", "button", "روشن", "On", "تشغيل"),
        ("btn.off", "button", "خاموش", "Off", "إيقاف"),
        ("btn.new_post", "button", "نوشته جدید", "New post", "مقال جديد"),
        ("btn.new_author", "button", "نویسنده جدید", "New author", "مؤلف جديد"),
        ("btn.save_settings", "button", "ذخیره تنظیمات", "Save settings", "حفظ الإعدادات"),

        ("home.title", "page", "نوشته‌ها", "Posts", "المقالات"),
        ("home.hero_title", "page", "یادداشت‌هایی درباره ساختن چیزها.", "Notes on building things.", "ملاحظات حول بناء الأشياء."),
        ("home.hero_body", "page",
            "نوشته‌های بلند، دقیقاً به همان سبکی که یک ریدمی نوشته می‌شود — مارک‌داون به‌عنوان ورودی، خروجی شیک و استایل‌دار، همراه با کد، تصویر و ویدیو دقیقاً درون متن.",
            "Long-form writing in the style of a README — Markdown in, polished output with code, images and video inline.",
            "كتابات طويلة بأسلوب ملف README — ماركداون كمدخل، ومخرجات أنيقة مع الكود والصور والفيديو داخل النص."),
        ("home.all", "page", "همه", "All", "الكل"),
        ("home.empty", "page", "هنوز نوشته‌ای منتشر نشده — اولین نوشته منتظر نوشته‌شدن است.", "No posts published yet — the first one is waiting to be written.", "لا توجد مقالات منشورة بعد."),
        ("home.draft", "page", "پیش‌نویس", "Draft", "مسودة"),

        ("admin.brand", "admin", "پنل مدیریت وبلاگ", "Blog Admin", "لوحة إدارة المدونة"),
        ("admin.panel", "admin", "پنل مدیریت", "Admin panel", "لوحة الإدارة"),
        ("admin.live", "admin", "زنده", "Live", "مباشر"),
        ("admin.live_title", "admin", "اتصال زنده به سرور", "Live connection to server", "اتصال مباشر بالخادم"),
        ("admin.back_to_site", "admin", "بازگشت به سایت", "Back to site", "العودة إلى الموقع"),
        ("admin.logout", "admin", "خروج از حساب", "Sign out", "تسجيل الخروج"),
        ("admin.demo", "admin", "دمو", "Demo", "تجريبي"),
        ("admin.super_only", "admin", "فقط ادمین", "Admin only", "للمدير فقط"),

        ("admin.group.general", "admin", "کلی", "General", "عام"),
        ("admin.group.content", "admin", "محتوا", "Content", "المحتوى"),
        ("admin.group.growth", "admin", "رشد و سئو", "Growth & SEO", "النمو وتحسين محركات البحث"),
        ("admin.group.account", "admin", "حساب", "Account", "الحساب"),
        ("admin.group.system", "admin", "سیستم", "System", "النظام"),

        ("admin.nav.dashboard", "admin", "داشبورد", "Dashboard", "لوحة التحكم"),
        ("admin.nav.moderation", "admin", "صف بررسی", "Moderation queue", "قائمة المراجعة"),
        ("admin.nav.posts", "admin", "نوشته‌ها", "Posts", "المقالات"),
        ("admin.nav.comments", "admin", "دیدگاه‌ها", "Comments", "التعليقات"),
        ("admin.nav.reports", "admin", "گزارش‌ها", "Reports", "التقارير"),
        ("admin.nav.media", "admin", "رسانه‌ها", "Media", "الوسائط"),
        ("admin.nav.taxonomy", "admin", "دسته‌ها و برچسب‌ها", "Categories & tags", "التصنيفات والوسوم"),
        ("admin.nav.analytics", "admin", "تحلیل‌ها", "Analytics", "التحليلات"),
        ("admin.nav.seo", "admin", "ابزارهای سئو", "SEO tools", "أدوات تحسين محركات البحث"),
        ("admin.nav.newsletter", "admin", "خبرنامه", "Newsletter", "النشرة"),
        ("admin.nav.profile", "admin", "پروفایل من", "My profile", "ملفي"),
        ("admin.nav.users", "admin", "مدیریت کاربران", "User management", "إدارة المستخدمين"),
        ("admin.nav.authors", "admin", "نویسندگان", "Authors", "المؤلفون"),
        ("admin.nav.settings", "admin", "تنظیمات سایت", "Site settings", "إعدادات الموقع"),
        ("admin.nav.flags", "admin", "پرچم‌های ویژگی", "Feature flags", "أعلام الميزات"),
        ("admin.nav.audit", "admin", "حسابرسی", "Audit log", "سجل التدقيق"),
        ("admin.nav.translations", "admin", "ترجمه‌های رابط", "UI translations", "ترجمات الواجهة"),

        ("page.comments", "page", "دیدگاه‌ها", "Comments", "التعليقات"),
        ("page.posts", "page", "نوشته‌ها", "Posts", "المقالات"),
        ("page.users", "page", "مدیریت کاربران", "User management", "إدارة المستخدمين"),
        ("page.audit", "page", "گزارش حسابرسی", "Audit log", "سجل التدقيق"),
        ("page.reports", "page", "گزارش‌های محتوا", "Content reports", "تقارير المحتوى"),
        ("page.moderation", "page", "صف بررسی", "Moderation queue", "قائمة المراجعة"),
        ("page.authors", "page", "نویسندگان", "Authors", "المؤلفون"),
        ("page.settings", "page", "تنظیمات سایت", "Site settings", "إعدادات الموقع"),
        ("page.flags", "page", "پرچم‌های ویژگی", "Feature flags", "أعلام الميزات"),

        ("col.index", "col", "#", "#", "#"),
        ("col.author", "col", "نویسنده", "Author", "المؤلف"),
        ("col.comment_body", "col", "متن دیدگاه", "Comment", "التعليق"),
        ("col.related_post", "col", "مربوط به نوشته", "Related post", "المقال المرتبط"),
        ("col.date", "col", "تاریخ", "Date", "التاريخ"),
        ("col.status", "col", "وضعیت", "Status", "الحالة"),
        ("col.actions", "col", "عملیات", "Actions", "إجراءات"),
        ("col.title", "col", "عنوان", "Title", "العنوان"),
        ("col.category", "col", "دسته‌بندی", "Category", "التصنيف"),
        ("col.features", "col", "ویژگی‌ها", "Features", "الميزات"),
        ("col.views", "col", "بازدید", "Views", "المشاهدات"),
        ("col.comments", "col", "دیدگاه‌ها", "Comments", "التعليقات"),
        ("col.user", "col", "کاربر", "User", "المستخدم"),
        ("col.roles", "col", "نقش‌ها", "Roles", "الأدوار"),
        ("col.posts", "col", "نوشته‌ها", "Posts", "المقالات"),
        ("col.registered", "col", "ثبت‌نام", "Registered", "التسجيل"),
        ("col.time", "col", "زمان", "Time", "الوقت"),
        ("col.action", "col", "اکشن", "Action", "الإجراء"),
        ("col.entity", "col", "موجودیت", "Entity", "الكيان"),
        ("col.details", "col", "جزئیات", "Details", "التفاصيل"),
        ("col.ip", "col", "IP", "IP", "IP"),
        ("col.target", "col", "هدف", "Target", "الهدف"),
        ("col.reason", "col", "دلیل", "Reason", "السبب"),
        ("col.reporter", "col", "گزارش‌دهنده", "Reporter", "المُبلِّغ"),
        ("col.display_name", "col", "نام نمایشی", "Display name", "الاسم المعروض"),
        ("col.username", "col", "نام کاربری", "Username", "اسم المستخدم"),
        ("col.email", "col", "ایمیل", "Email", "البريد"),
        ("col.role", "col", "نقش", "Role", "الدور"),
        ("col.post_count", "col", "تعداد نوشته", "Post count", "عدد المقالات"),
        ("col.feature", "col", "ویژگی", "Feature", "الميزة"),
        ("col.key", "col", "کلید", "Key", "المفتاح"),
        ("col.updated", "col", "آخرین تغییر", "Last updated", "آخر تحديث"),

        ("dt.processing", "dt", "در حال بارگذاری…", "Loading…", "جارٍ التحميل…"),
        ("dt.search", "dt", "جست‌وجو", "Search", "بحث"),
        ("dt.search_placeholder", "dt", "جست‌وجو…", "Search…", "بحث…"),
        ("dt.length_menu", "dt", "نمایش _MENU_", "Show _MENU_", "عرض _MENU_"),
        ("dt.info", "dt", "نمایش _START_ تا _END_ از _TOTAL_", "Showing _START_ to _END_ of _TOTAL_", "عرض _START_ إلى _END_ من _TOTAL_"),
        ("dt.info_empty", "dt", "موردی نیست", "No entries", "لا توجد عناصر"),
        ("dt.info_filtered", "dt", "(فیلتر از _MAX_)", "(filtered from _MAX_)", "(مصفى من _MAX_)"),
        ("dt.zero_records", "dt", "نتیجه‌ای یافت نشد", "No matching records", "لا توجد نتائج"),
        ("dt.empty_table", "dt", "جدولی خالی است", "No data", "الجدول فارغ"),
        ("dt.paginate_first", "dt", "اول", "First", "الأول"),
        ("dt.paginate_last", "dt", "آخر", "Last", "الأخير"),
        ("dt.paginate_next", "dt", "بعدی", "Next", "التالي"),
        ("dt.paginate_previous", "dt", "قبلی", "Previous", "السابق"),

        ("status.open", "status", "باز", "Open", "مفتوح"),
        ("status.resolved", "status", "حل‌شده", "Resolved", "محلول"),
        ("status.dismissed", "status", "ردشده", "Dismissed", "مرفوض"),
        ("status.pending", "status", "در انتظار", "Pending", "قيد الانتظار"),
        ("status.approved", "status", "تأییدشده", "Approved", "موافق عليه"),
        ("status.rejected", "status", "ردشده", "Rejected", "مرفوض"),
        ("status.published", "status", "منتشر", "Published", "منشور"),
        ("status.published_full", "status", "منتشرشده", "Published", "منشور"),
        ("status.draft", "status", "پیش‌نویس", "Draft", "مسودة"),
        ("status.active", "status", "فعال", "Active", "نشط"),
        ("status.inactive", "status", "غیرفعال", "Inactive", "غير نشط"),
        ("status.locked", "status", "قفل", "Locked", "مقفل"),
        ("status.deleted", "status", "حذف‌شده", "Deleted", "محذوف"),
        ("status.scheduled", "status", "زمان‌بندی", "Scheduled", "مجدول"),
        ("status.featured", "status", "ویژه", "Featured", "مميز"),
        ("status.sticky", "status", "چسبان", "Sticky", "مثبت"),

        ("tab.all", "tab", "همه", "All", "الكل"),
        ("tab.pending", "tab", "در انتظار", "Pending", "قيد الانتظار"),
        ("tab.approved", "tab", "تأییدشده", "Approved", "موافق عليه"),
        ("tab.rejected", "tab", "ردشده", "Rejected", "مرفوض"),
        ("tab.open", "tab", "باز", "Open", "مفتوح"),
        ("tab.resolved", "tab", "حل‌شده", "Resolved", "محلول"),
        ("tab.dismissed", "tab", "ردشده", "Dismissed", "مرفوض"),

        ("mod.pending_comments", "mod", "دیدگاه‌های در انتظار", "Pending comments", "تعليقات قيد الانتظار"),
        ("mod.no_pending_comments", "mod", "دیدگاه معلقی نیست.", "No pending comments.", "لا توجد تعليقات معلقة."),
        ("mod.open_reports", "mod", "گزارش‌های باز", "Open reports", "بلاغات مفتوحة"),
        ("mod.no_open_reports", "mod", "گزارش بازی نیست.", "No open reports.", "لا توجد بلاغات مفتوحة."),
        ("mod.all_comments", "mod", "همه دیدگاه‌ها", "All comments", "كل التعليقات"),
        ("mod.all_reports", "mod", "همه گزارش‌ها", "All reports", "كل البلاغات"),
        ("mod.target_post", "mod", "نوشته", "Post", "مقال"),
        ("mod.target_comment", "mod", "دیدگاه", "Comment", "تعليق"),

        ("authors.subtitle", "page", "مدیریت نویسندگان وبلاگ (فقط سوپر ادمین)", "Manage blog authors (SuperAdmin only)", "إدارة مؤلفي المدونة (للمدير الأعلى فقط)"),
        ("authors.empty_title", "page", "نویسنده‌ای یافت نشد", "No authors found", "لا يوجد مؤلفون"),
        ("authors.empty_body", "page", "اولین نویسنده را اضافه کنید.", "Add the first author.", "أضف أول مؤلف."),
        ("authors.posts_suffix", "page", "نوشته", "posts", "مقالات"),

        ("settings.section_seo", "form", "عمومی و سئو", "General & SEO", "عام وتحسين محركات البحث"),
        ("settings.site_name", "form", "نام سایت", "Site name", "اسم الموقع"),
        ("settings.site_description", "form", "توضیح سایت", "Site description", "وصف الموقع"),
        ("settings.author_name", "form", "نام نویسنده پیش‌فرض", "Default author name", "اسم المؤلف الافتراضي"),
        ("settings.twitter", "form", "توییتر", "Twitter", "تويتر"),
        ("settings.base_url", "form", "آدرس پایه", "Base URL", "الرابط الأساسي"),
        ("settings.section_maintenance", "form", "حالت نگهداری", "Maintenance mode", "وضع الصيانة"),
        ("settings.maintenance_enable", "form", "فعال‌سازی حالت نگهداری (فقط SuperAdmin عبور می‌کند)", "Enable maintenance (SuperAdmin only can pass)", "تفعيل وضع الصيانة (المدير الأعلى فقط)"),
        ("settings.maintenance_message", "form", "پیام نگهداری", "Maintenance message", "رسالة الصيانة"),
        ("settings.section_announcement", "form", "بنر اعلان سراسری", "Site-wide announcement banner", "شريط إعلان عام"),
        ("settings.announcement_enable", "form", "نمایش بنر در بالای سایت", "Show banner at top of site", "إظهار الشريط أعلى الموقع"),
        ("settings.announcement_text", "form", "متن بنر", "Banner text", "نص الشريط"),
        ("settings.announcement_style", "form", "سبک", "Style", "النمط"),
        ("settings.style_info", "form", "اطلاع", "Info", "معلومة"),
        ("settings.style_warn", "form", "هشدار", "Warning", "تحذير"),
        ("settings.style_success", "form", "موفقیت", "Success", "نجاح"),
        ("flags.help", "page", "بدون redeploy ویژگی‌ها را روشن/خاموش کنید.", "Toggle features without redeploy.", "تشغيل/إيقاف الميزات دون إعادة نشر."),

        ("post.comments", "page", "دیدگاه‌ها", "Comments", "التعليقات"),
        ("post.sort", "page", "مرتب‌سازی", "Sort", "ترتيب"),
        ("post.sort_relevant", "page", "مرتبط (پسندها)", "Relevant (likes)", "الأكثر صلة"),
        ("post.sort_latest", "page", "جدیدترین", "Latest", "الأحدث"),
        ("post.reading_min", "page", "دقیقه مطالعه", "min read", "دقيقة قراءة"),
        ("post.views", "page", "بازدید", "views", "مشاهدة"),
        ("post.featured", "page", "ویژه", "Featured", "مميز"),
        ("post.sticky", "page", "چسبان", "Sticky", "مثبت"),
        ("post.comment_name", "form", "نام شما", "Your name", "اسمك"),
        ("post.comment_body", "form", "متن دیدگاه…", "Write a comment…", "اكتب تعليقاً…"),
        ("post.comment_send", "form", "ارسال دیدگاه", "Post comment", "نشر التعليق"),
        ("post.report_reason", "form", "دلیل گزارش", "Report reason", "سبب الإبلاغ"),
        ("post.report_send", "form", "ارسال گزارش", "Submit report", "إرسال البلاغ"),

        ("auth.login", "auth", "ورود", "Login", "دخول"),
        ("auth.register", "auth", "ثبت‌نام", "Register", "تسجيل"),
        ("auth.email", "auth", "ایمیل", "Email", "البريد"),
        ("auth.password", "auth", "رمز عبور", "Password", "كلمة المرور"),
        ("auth.username", "auth", "نام کاربری", "Username", "اسم المستخدم"),

        ("msg.saved", "message", "ذخیره شد.", "Saved.", "تم الحفظ."),
        ("msg.empty", "message", "موردی یافت نشد.", "Nothing found.", "لا توجد عناصر."),
        ("msg.confirm_delete", "message", "آیا مطمئن هستید؟", "Are you sure?", "هل أنت متأكد؟"),
        ("msg.confirm_trash", "message", "انتقال به سطل زباله؟", "Move to trash?", "نقل إلى سلة المهملات؟"),
        ("msg.confirm_delete_comment", "message", "این دیدگاه برای همیشه حذف شود؟", "Permanently delete this comment?", "حذف هذا التعليق نهائياً؟"),
        ("msg.analytics_reset", "message", "آمار بازدید پاک شد. از این به بعد فقط بازدیدهای واقعی ثبت می‌شوند.", "View stats cleared. Only real visits will be recorded from now on.", "تم مسح إحصاءات المشاهدة."),
        ("msg.scope_all", "message", "همه نویسندگان", "All authors", "كل المؤلفين"),
        ("msg.scope_mine", "message", "فقط نوشته‌های من", "My posts only", "مقالاتي فقط"),
        ("msg.uncategorized", "message", "بدون دسته", "Uncategorized", "بدون تصنيف"),
        ("msg.dash", "message", "—", "—", "—"),

        ("notif.title", "notif", "اعلان‌ها", "Notifications", "الإشعارات"),
        ("notif.mark_all", "notif", "خواندن همه", "Mark all read", "تحديد الكل كمقروء"),
        ("notif.view_all", "notif", "مشاهده همه", "View all", "عرض الكل"),
        ("notif.preferences", "notif", "تنظیمات", "Preferences", "التفضيلات"),
        ("notif.loading", "notif", "در حال بارگذاری…", "Loading…", "جارٍ التحميل…"),
        ("notif.empty", "notif", "اعلانی نیست.", "No notifications", "لا توجد إشعارات."),
        ("notif.failed", "notif", "بارگذاری ناموفق", "Failed to load", "فشل التحميل"),
        ("notif.mark_read", "notif", "خواندم", "Mark read", "تمت القراءة"),
        ("notif.view", "notif", "مشاهده", "View", "عرض"),
        ("notif.prefs_title", "notif", "تنظیمات اعلان", "Notification settings", "إعدادات الإشعارات"),
        ("notif.channels", "notif", "کانال‌ها", "Channels", "القنوات"),
        ("notif.channel_email", "notif", "ایمیل", "Email", "البريد"),
        ("notif.channel_inapp", "notif", "اعلان داخل سایت", "In-app", "داخل الموقع"),
        ("notif.channel_push", "notif", "پوش (نیاز به پیکربندی VAPID)", "Push (needs VAPID)", "دفع (يتطلب VAPID)"),
        ("notif.channel_sms", "notif", "پیامک تبلیغاتی", "SMS ads", "رسائل SMS"),
        ("notif.phone", "notif", "شماره موبایل (E.164)", "Mobile (E.164)", "الجوال (E.164)"),
        ("notif.phone_help", "notif", "برای SMS تبلیغات — سرویس‌دهنده را خودتان در Sms:* تنظیم کنید.", "For SMS ads — configure your provider under Sms:*.", "لإعلانات SMS — اضبط المزود في Sms:*."),
        ("notif.events", "notif", "رویدادها", "Events", "الأحداث"),
        ("notif.event_comment", "notif", "دیدگاه جدید روی نوشته‌های من", "New comment on my posts", "تعليق جديد على مقالاتي"),
        ("notif.event_follower", "notif", "دنبال‌کننده جدید", "New follower", "متابع جديد"),
        ("notif.event_digest", "notif", "خلاصه هفتگی ایمیل", "Weekly email digest", "ملخص أسبوعي بالبريد"),
        ("notif.admin_title", "notif", "ارسال اعلان", "Send notifications", "إرسال الإشعارات"),
        ("notif.form_title", "notif", "عنوان", "Title", "العنوان"),
        ("notif.form_body", "notif", "متن", "Body", "النص"),
        ("notif.form_link", "notif", "لینک (اختیاری)", "Link (optional)", "رابط (اختياري)"),
        ("notif.form_audience", "notif", "مخاطب", "Audience", "الجمهور"),
        ("notif.form_kind", "notif", "نوع", "Kind", "النوع"),
        ("notif.form_category", "notif", "دسته (برای خوانندگان دسته)", "Category (for category readers)", "التصنيف (لقراء التصنيف)"),
        ("notif.form_target_user", "notif", "شناسه کاربر هدف (تکی)", "Target user id (single)", "معرّف المستخدم (فردي)"),
        ("notif.form_target_csv", "notif", "شناسه‌های کاربر CSV (دسته‌ای)", "User ids CSV (batch)", "معرّفات المستخدمين CSV"),
        ("notif.form_author", "notif", "شناسه نویسنده (مخاطب دنبال‌کنندگان)", "Author id (followers audience)", "معرّف المؤلف (المتابعون)"),
        ("notif.form_schedule", "notif", "زمان‌بندی برای بعد", "Schedule for later", "جدولة لاحقاً"),
        ("notif.form_scheduled_at", "notif", "زمان UTC", "Scheduled UTC", "الوقت UTC"),
        ("notif.form_send", "notif", "ارسال / زمان‌بندی", "Send / schedule", "إرسال / جدولة"),
        ("notif.author_help", "notif", "می‌توانید به دنبال‌کنندگان خود اعلان بفرستید (مثلاً درباره نوشته جدید).", "You can notify users who follow you (e.g. about a new post).", "يمكنك إشعار متابعيك (مثلاً بمقال جديد)."),
        ("notif.aud_authors", "notif", "همه نویسندگان", "All authors", "كل المؤلفين"),
        ("notif.aud_broadcast", "notif", "همه (پخش عمومی)", "Everyone (broadcast)", "الجميع (بث)"),
        ("notif.aud_category", "notif", "خوانندگان دسته", "Category readers", "قراء التصنيف"),
        ("notif.aud_followers", "notif", "دنبال‌کنندگان نویسنده", "Author followers", "متابعو المؤلف"),
        ("notif.aud_single", "notif", "یک کاربر", "Single user", "مستخدم واحد"),
        ("notif.aud_list", "notif", "لیست کاربران (CSV)", "User list (CSV ids)", "قائمة مستخدمين (CSV)"),
        ("notif.kind_admin", "notif", "پیام ادمین", "Admin message", "رسالة المدير"),
        ("notif.kind_broadcast", "notif", "پخش عمومی", "Broadcast", "بث"),
        ("notif.kind_category", "notif", "دسته", "Category batch", "دفعة تصنيف"),
        ("notif.kind_system", "notif", "سیستم", "System", "نظام"),
        ("notif.kind_ad", "notif", "کمپین تبلیغاتی", "Ad campaign", "حملة إعلانية"),
        ("notif.recent_campaigns", "notif", "کمپین‌های اخیر", "Recent campaigns", "الحملات الأخيرة"),
        ("notif.no_campaigns", "notif", "هنوز کمپینی نیست.", "No campaigns yet.", "لا توجد حملات بعد."),
        ("notif.col_recipients", "notif", "گیرندگان", "Recipients", "المستلمون"),
        ("notif.status_sent", "notif", "ارسال‌شده", "Sent", "مُرسَل"),

        ("dash.range_7", "dash", "۷ روز اخیر", "Last 7 days", "آخر 7 أيام"),
        ("dash.range_30", "dash", "۳۰ روز اخیر", "Last 30 days", "آخر 90 يوماً"),
        ("dash.range_90", "dash", "۹۰ روز اخیر", "Last 90 days", "آخر 90 يوماً"),
        ("dash.reset_btn", "dash", "ریست آمار بازدید", "Reset view stats", "إعادة ضبط الإحصاءات"),
        ("dash.reset_title", "dash", "پاک‌کردن بازدیدهای قدیمی/دمو", "Clear old/demo view stats", "مسح إحصاءات قديمة"),
        ("dash.reset_confirm", "dash", "همه آمار بازدید پاک شود؟ این کار قابل بازگشت نیست.", "Clear all view stats? This cannot be undone.", "مسح كل إحصاءات المشاهدة؟ لا يمكن التراجع."),
        ("dash.kpi_views_range", "dash", "بازدید در بازه انتخاب‌شده", "Views in selected range", "المشاهدات في الفترة"),
        ("dash.vs_previous", "dash", "نسبت به بازه قبلی", "vs previous period", "مقارنة بالفترة السابقة"),
        ("dash.kpi_views_today", "dash", "بازدید امروز", "Views today", "مشاهدات اليوم"),
        ("dash.kpi_views_total", "dash", "بازدید کل تاریخی", "All-time views", "إجمالي المشاهدات"),
        ("dash.kpi_pending", "dash", "دیدگاه‌های در انتظار بررسی", "Pending comments", "تعليقات قيد المراجعة"),
        ("dash.view_moderation", "dash", "مشاهده در صف مدیریت ›", "Open moderation queue ›", "فتح قائمة المراجعة ›"),
        ("dash.kpi_approved", "dash", "دیدگاه‌های تأییدشده", "Approved comments", "تعليقات موافق عليها"),
        ("dash.kpi_rejected", "dash", "دیدگاه‌های ردشده", "Rejected comments", "تعليقات مرفوضة"),
        ("dash.kpi_media", "dash", "فایل‌های رسانه", "Media files", "ملفات الوسائط"),
        ("dash.kpi_media_size", "dash", "حجم رسانه‌های ذخیره‌شده", "Stored media size", "حجم الوسائط"),
        ("dash.chart_views_title", "dash", "روند بازدید", "Views trend", "اتجاه المشاهدات"),
        ("dash.chart_views_sub", "dash", "تعداد بازدید واقعی خوانندگان در {0} روز اخیر · به‌روز‌رسانی زنده", "Real reader views over the last {0} days · live", "مشاهدات حقيقية خلال آخر {0} يوماً · مباشر"),
        ("dash.chart_views_label", "dash", "بازدید", "Views", "المشاهدات"),
        ("dash.chart_comments_title", "dash", "وضعیت دیدگاه‌ها", "Comment status", "حالة التعليقات"),
        ("dash.chart_comments_sub", "dash", "تأییدشده / در انتظار / ردشده", "Approved / Pending / Rejected", "موافق / قيد الانتظار / مرفوض"),
        ("dash.chart_posts_title", "dash", "نوشته‌های ایجادشده", "Posts created", "المقالات المنشأة"),
        ("dash.chart_posts_sub", "dash", "۶ ماه اخیر", "Last 6 months", "آخر 6 أشهر"),
        ("dash.chart_cat_title", "dash", "نوشته‌ها بر اساس دسته‌بندی", "Posts by category", "المقالات حسب التصنيف"),
        ("dash.chart_cat_sub", "dash", "توزیع کل نوشته‌ها", "Distribution of all posts", "توزيع كل المقالات"),
        ("dash.chart_fail", "dash", "بارگذاری کتابخانه نمودار ناموفق بود.", "Chart library failed to load.", "فشل تحميل مكتبة الرسوم."),
        ("dash.top_posts", "dash", "پربازدیدترین نوشته‌ها", "Top posts", "أكثر المقالات مشاهدة"),
        ("dash.view_all_posts", "dash", "مشاهده همه نوشته‌ها", "View all posts", "عرض كل المقالات"),
        ("dash.top_empty_title", "dash", "هنوز داده‌ای برای نمایش نیست", "No data to show yet", "لا توجد بيانات بعد"),
        ("dash.top_empty_body", "dash", "وقتی نوشته‌ها بازدید بگیرند، رتبه‌بندی همین‌جا نمایش داده می‌شود.", "When posts get views, rankings appear here.", "عند حصول المقالات على مشاهدات تظهر الترتيبات هنا."),
        ("dash.col_views_total", "dash", "بازدید کل", "Total views", "إجمالي المشاهدات"),
        ("dash.col_views_range", "dash", "بازدید در بازه", "Views in range", "المشاهدات في الفترة"),
        ("dash.recent_comments", "dash", "آخرین دیدگاه‌ها", "Recent comments", "أحدث التعليقات"),
        ("dash.view_all", "dash", "مشاهده همه", "View all", "عرض الكل"),
        ("dash.comments_empty_title", "dash", "هنوز دیدگاهی ثبت نشده", "No comments yet", "لا تعليقات بعد"),
        ("dash.comments_empty_body", "dash", "وقتی خواننده‌ای دیدگاهی بگذارد، همین‌جا نمایش داده می‌شود.", "When a reader leaves a comment, it shows up here.", "عند ترك قارئ تعليقاً يظهر هنا."),
    };
}
