<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Blog.Core.Contract</RootNamespace>
    <AssemblyName>Blog.Core.Contract</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Blog.Core.Domain\Blog.Core.Domain.csproj" />
  </ItemGroup>
</Project>
