<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Blog.Infra.Plugins</RootNamespace>
    <AssemblyName>Blog.Infra.Plugins</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\Core\Blog.Core.Contract\Blog.Core.Contract.csproj" />
  </ItemGroup>
</Project>
